freedom:
  ros__parameters:
    sensor:
      min_range: 0.0
      max_range: 40.0
      min_z: -5.0
      max_z: 5.0

    map:
      sub_voxel_size: 0.05
      voxel_depth: 2
      block_depth: 5
      enable_local_map: false
      local_map_range: 50.0
      local_map_min_z: -20.0
      local_map_max_z: 20.0
      raycast_max_range: 10.0
      raycast_min_z: -3.0
      raycast_max_z: 3.0
      counts_to_free: 3
      counts_to_revert: 20
      conservative_connectivity: 26
      aggressive_connectivity: 124

    raycast_enhancement:
      enable_raycast_enhancement: false

    num_threads: 8
